Metrics/MethodLength:
  Max: 16

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**'

Style/StringLiterals:
  EnforcedStyle: double_quotes
