# The name of the check that will be created
# Default: 'Rubocop Action'
check_name: "Rubocop Results"
# Version of rubocop that will be installed.
# Valid options: 'latest' or a version number like '0.75.0'
# Default: 'latest'
rubocop_version: 'latest'
# Extensions required to run your rubocop config.
# Valid options: any rubocop extension, by default the latest
# gem version will be used. You can explicitly state that or use a version
# number like '1.5.1'
# Default: none
rubocop_extensions:
  - 'rubocop-rails'
  - 'rubocop-performance': '1.5.1'
  - 'rubocop-minitest': 'latest'
  - 'rubocop-rspec': '1.37.0'
# Rubocop configuration file path relative to the workspace
# Valid options: a path like 'config/.rubocop.yml'
# Default: none, Rubocop will automatically look at '.rubocop.yml' or use it's defaults
rubocop_config_path: '.rubocop.yml'
# List of cops you would like to exclude if they are not specified in '.rubocop.yml'
# Valid options: list of valid cops (see Rubocop documentation for cop names)
# Default: none
rubocop_excluded_cops:
  - 'Style/FrozenStringLiteralComment'
# Minimum severity for exit with error code
# Valid options: 'refactor', 'convention', 'warning', 'error', or 'fatal'.
# Default: 'warning'
rubocop_fail_level: 'warning'
# Instead of installing gems from rubygems, we can run 'bundle install' on your project,
# you would need to do this if you are using something like 'rubocop-github' or if you don't
# want to list out extensions
# Valid options: true or false
# Default: false
bundle: false
# The scope of code that Rubocop should lint. Use this if you only want
# to lint changed files
# Valid options: 'modified'
# Default: none, aka Rubocop is run against the entire codebase
check_scope: 'modified'
# Ability to toggle running autocorrect in the rubocop command.
# If there are failing lints, the action will push them to the branch.
# Valid options: 'unsafe', 'safe', false
# Default: false
autocorrect: 'safe'
# Commit message for autocorrect commits. Not needed
# if autocorrect does not equal 'safe' or 'unsafe'
# Valid options: a string like 'fix cops'
# Default: 'Rubocop Linter Action: autocorrect cops'
autocorrect_commit_message: 'Rubocop Linter Action: autocorrect cops'
