name: Build

on: [push]

jobs:
  build:
    name: Action CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: docker build . --tag my-image-name:$(date +%s)
    - name: Verify action syntax
      # The action should not publish any real changes, but should succeed.
      uses: './'
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        branch: '${{ github.ref }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
