name: Build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  build:
    name: Action CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Verify action syntax
      uses: './'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
