name: Linters

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  rubocop:
    name: Ruocop Action
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run Rubocop
        run: bin/rubocop
  shell_linter:
    name: Shell Lint Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Shell Linter
        uses: azohra/shell-linter@v0.1.0
