name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  test:
    name: Rspec Test Action
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: actions/cache@v1.0.3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --deployment
    - name: Run Rspec
      run: bin/rspec
