name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  test:
    name: Rspec Test Action
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.7
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: 2.7
    - uses: actions/cache@v1.0.3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Bundle
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run Rspec
      run: bin/test
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
